# Generated by Django 6.0 on 2025-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('docket_number', models.CharField(blank=True, max_length=100)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('parties', models.TextField(blank=True, help_text='Short description of parties involved')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary_short', models.TextField(blank=True, help_text='Concise summary (1-2 sentences)')),
                ('summary_long', models.TextField(blank=True, help_text='Full case summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-decision_date', '-created_at'],
            },
        ),
    ]
